services:
  web:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-commerce-container
    entrypoint: []
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8001

    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
  db:
    image: postgres:16
    container_name: postgres-container
    environment:
      - POSTGRES_DB=nexus_commerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - postgresdb_docker:/var/lib/postgresql/data/
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgresdb_docker:
