# Generated by Django 5.2.10 on 2026-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                ("gender", models.CharField(max_length=10)),
            ],
        ),
    ]
