# Generated by Django 5.2.10 on 2026-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="payment",
            name="tx_ref",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("fashion", "Fashion"),
                    ("home_kitchen", "Home & Kitchen"),
                    ("beauty_care", "Beauty & Personal Care"),
                    ("sports_outdoors", "Sports & Outdoors"),
                    ("health_wellness", "Health & Wellness"),
                    ("automotive", "Automotive"),
                    ("books_media", "Books & Media"),
                    ("toys_games", "Toys & Games"),
                    ("groceries", "Groceries"),
                    ("office_supplies", "Office Supplies"),
                    ("pet_supplies", "Pet Supplies"),
                    ("others", "Others"),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="commerce_or_user_id_766724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product"], name="commerce_or_order_i_045869_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "paid_at"], name="commerce_pa_user_id_5fce61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="commerce_pr_price_c1dc59_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="commerce_us_email_8f39fb_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="commerce_us_usernam_726991_idx"
            ),
        ),
    ]
