# Generated by Django 5.2.10 on 2026-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_alter_user_options_payment_tx_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("cancel", "Cancel"),
                    ("paid", "Paid"),
                    ("confirmed", "Confirmed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
