# Generated by Django 5.2.10 on 2026-08-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_alter_payment_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="commerce_or_user_id_766724_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tx_ref",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("Failed", "Failed"),
                    ("Refund", "Refund"),
                    ("Returned", "Returned"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at", "tx_ref"],
                name="commerce_or_user_id_e79017_idx",
            ),
        ),
    ]
